[versions]
androidGradlePlugin = "8.0.0"
androidxActivity = "1.5.1"
androidxCompose = "1.3.0"
androidxComposeCompiler = "1.4.1"
androidxCore = "1.9.0"
androidxCoreTesting = "2.1.0"
androidxEspresso = "3.4.0"
androidxLifecycle = "2.3.1"
androidxTestExt = "1.1.2"
arcGIS = "200.2.0-3869"
compileSdk = "33"
compose-material3 = "1.0.0"
junit = "4.13.2"
kotlin = "1.8.0"
minSdk = "26"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxCompose" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidxCompose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidxCompose" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxCompose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
arcgis = { group = "com.esri", name = "arcgis-maps-kotlin", version.ref = "arcGIS" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
core = [
    "androidx-core-ktx"
]

composeCore = [
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "arcgis"
]

composeTest = [
    "androidx-test-ext",
    "androidx-test-espresso-core",
    "androidx-compose-ui-test"
]

debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest"
]

unitTest = [
    "junit"
]


