[versions]
androidGradlePlugin = "8.2.0"
androidxActivity = "1.8.1"
androidXBrowser = "1.7.0"
composeBOM = "2023.10.01"
androidxComposeCompiler = "1.5.4"
androidxCore = "1.12.0"
androidxEspresso = "3.5.1"
androidxLifecycle = "2.6.2"
androidxLifecycleRuntimeCompose = "2.7.0-rc01"
androidxTestExt = "1.1.5"
androidxViewmodelCompose = "2.6.2"
compileSdk = "34"
junit = "4.13.2"
kotlin = "1.9.20"
minSdk = "26"
kotlinxCoroutinesTest = "1.7.3"
kotlinxSerializationJson = "1.5.1"
truth = "1.1.4"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidXBrowser"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBOM" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime"}
androidx-compose-material3 = { module = "androidx.compose.material3:material3"}
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxViewmodelCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycleRuntimeCompose"}
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin"}
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradle-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version = "2.0.1"}
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
core = [
    "androidx-core-ktx"
]

composeCore = [
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-lifecycle-viewmodel-compose"
]

composeTest = [
    "androidx-test-ext",
    "androidx-test-espresso-core",
    "androidx-compose-ui-test"
]

debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest"
]

serialization = [
    "kotlinx-serialization-core",
    "kotlinx-serialization-json",
    "kotlin-reflect"
]

unitTest = [
    "junit",
    "kotlinx-coroutines-test",
    "truth"
]


